#Enter Configurations for curve values you would like to analyze
#TODO Add units config and explain in read me that the runner assumes that the units are configed and not written into title.
Curve_configs:
  BDEP:
    Dtype: float
    upLim: 20001.0
    lowLim: -0.0001
  BHT:
    Dtype: float
    upLim: 100.0
    lowLim: -0.0001
  CTOR:
    Dtype: float
    upLim: 100.0
    lowLim: -0.0001
  DEPT:
    Dtype: float
    upLim: 20000.0
    lowLim: -0.0001
  RPM:
    Dtype: float
    upLim: 300.0
    lowLim: -0.0001
General_configs:
  DataFile: 'example.csv'
  CheckFile: 'consistency_check.csv'
  CalcConsistency: True
  freqTol: 1.1
Accuracy_configs:
  Curves:
    BDEP: BHT
    BHT: BDEP
  Tolerance: 1.1
Dimension_weights:
  Validity: 35
  Frequency: 25
  Consistency: 5
  Completeness: 5
  Uniqueness: 5
  Accuracy: 25